//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMandiola2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial_Transaccion
    {
        public int ID { get; set; }
        public int ID_Consecutivo { get; set; }
        public int ID_Cliente { get; set; }
        public int Metodo_pago { get; set; }
        public int Monto { get; set; }
        public Nullable<int> ID_Habitacion { get; set; }
        public Nullable<int> ID_Articulo { get; set; }
    }
}
